name: DiggyHole
version: 0.2.1
author: WatcherWhale
main: ww.bewhaled.diggyhole.Main
depends: [WorldEdit]
api-version: 1.14

commands:
  dh:
    description: Diggyhole commands
    usage: /dh <command>
  diggyhole:
    description: Diggyhole commands
    usage: /dh <command>